#!/usr/bin/env bash
set -eu

script_path=$(realpath "$BASH_SOURCE")
repo_dir=$(dirname "$script_path")
build_dir="$repo_dir/docker"
root_fs="$build_dir/root-fs"

function main() {
  if [[ $# -lt 1 ]]; then
    fatal 'no command given'
  fi

  local command="$1"
  shift

  case "$command" in
    test-unit) test_unit "$@" ;;
    test-acceptance) test_acceptance "$@" ;;
    test-build) test_env_build "$@" ;;
    test-clean) test_env_clean "$@" ;;
    *) fatal 'invalid command' ;;
  esac
}

function fatal() {
  echo "error: $@"
  exit 1
}

function log() {
  echo "---> $@"
}

function test_unit() {
  test_env_build

  log 'running unit tests'
  docker run -ti --rm \
    -e GOPATH=/home/aurgo/go \
    -v "$repo_dir:/home/aurgo/go/src/github.com/ooesili/aurgo" \
    ooesili/aurgo \
    go test -v github.com/ooesili/aurgo/internal/...
}

function test_acceptance() {
  test_env_build

  log 'running acceptance tests'
  docker run --privileged -ti --rm \
    -e GOPATH=/home/aurgo/go \
    -v "$repo_dir:/home/aurgo/go/src/github.com/ooesili/aurgo" \
    ooesili/aurgo \
    go test -v github.com/ooesili/aurgo/test/acceptance
}

function test_env_build() {
  create_root_fs
  import_base_image
  build_aurgo_image
}

function test_env_clean() {
  delete_rootfs
  remove_docker_image ooesili/aurgo
  remove_docker_image ooesili/arch-base
}

function create_root_fs() {
  log 'creating docker filesystem'
  if [[ ! -d "$root_fs" ]]; then
    mkarchroot "$root_fs" base-devel devtools go git
  else
    echo 'already exists, nothing to do'
  fi
}

function build_aurgo_image() {
  log 'building docker image'
  docker build -t ooesili/aurgo "$build_dir"
}

function import_base_image() {
  log 'building Arch Linux base image'
  if ! does_image_exist ooesili/arch-base; then
    sudo tar cf - -C "$root_fs" . | docker import - ooesili/arch-base
  else
    echo 'already exists, nothing to do'
  fi
}

function delete_rootfs() {
  log 'deleting root-fs'
  sudo rm -rf "$root_fs"
  sudo rm -f "$root_fs.lock"
}

function remove_docker_image() {
  local image_name="$1"

  log "deleting docker image $1"
  if does_image_exist "$image_name"; then
    docker rmi "$image_name"
  else
    echo 'already removed, nothing to do'
  fi
}

function does_image_exist() {
  local image_name="$1"
  [[ -n $(docker images -q "$image_name") ]]
}

main "$@"
