---
- name: install required packages
  package: "name={{ item }} state=installed"
  become: true
  with_items:
  - git
  - go
  - devtools

- name: install bashrc
  template: src=bashrc dest=/home/vagrant/.bashrc

- name: install motd
  copy: src=motd dest=/etc/motd
  become: true

- name: create and chown GOPATH directories
  file: "path={{ item }} state=directory owner=vagrant"
  become: true
  with_items:
  - "{{ GOPATH }}"
  - "{{ GOPATH }}/bin"
  - "{{ GOPATH }}/src"
  - "{{ GOPATH }}/src/github.com"
  - "{{ GOPATH }}/src/github.com/ooesili"

- name: create temporary directory for acceptance tests
  file: path=/home/vagrant/.tmp state=directory

- name: install glide
  shell: |
    source ~/.bashrc
    curl https://glide.sh/get | sh
  args:
    creates: "{{ GOPATH }}/bin/glide"

- name: install ginkgo
  shell: |
    source ~/.bashrc
    go get github.com/onsi/ginkgo/ginkgo
  args:
    creates: "{{ GOPATH }}/bin/ginkgo"
